import { useCallback, useEffect, useMemo, useState } from "react";
import {
  completeWeeklyDigest,
  getWeeklyDigestTopic,
  listWeeklyDigests,
  setWeeklyDigestTopic,
} from "../api/client";
import RubyHtml from "../components/RubyHtml";
import * as L from "../lib/uiLabelsRuby";
import type { WeeklyDigest } from "../types";

function preview(content: string): string {
  const t = content.trim();
  if (t.length <= 120) return t;
  return `${t.slice(0, 120)}…`;
}

export default function DigestsPage() {
  const [topic, setTopic] = useState("");
  const [topicInput, setTopicInput] = useState("");
  const [digests, setDigests] = useState<WeeklyDigest[]>([]);
  const [expandedId, setExpandedId] = useState("");
  const [editingTopic, setEditingTopic] = useState(false);
  const [loading, setLoading] = useState(true);
  const [savingTopic, setSavingTopic] = useState(false);
  const [busyDigestId, setBusyDigestId] = useState("");
  const [err, setErr] = useState("");
  const [autoGeneratedOnOpen, setAutoGeneratedOnOpen] = useState(false);

  const load = useCallback(async () => {
    setLoading(true);
    setErr("");
    try {
      const [t, d] = await Promise.all([getWeeklyDigestTopic(), listWeeklyDigests()]);
      const nextTopic = (d.topic || t.topic || "").trim();
      setTopic(nextTopic);
      if (!editingTopic) setTopicInput(nextTopic);
      setDigests(d.digests || []);
      setAutoGeneratedOnOpen(!!d.autoGeneratedOnOpen);
    } catch (e) {
      setErr(e instanceof Error ? e.message : "エラー");
    } finally {
      setLoading(false);
    }
  }, [editingTopic]);

  useEffect(() => {
    void load();
  }, [load]);

  const hasTopic = topic.trim() !== "";
  const canSaveTopic = topicInput.trim() !== "";

  const saveTopic = async () => {
    if (!canSaveTopic) return;
    setSavingTopic(true);
    setErr("");
    try {
      const t = topicInput.trim();
      await setWeeklyDigestTopic(t);
      setTopic(t);
      setEditingTopic(false);
      await load();
    } catch (e) {
      setErr(e instanceof Error ? e.message : "エラー");
    } finally {
      setSavingTopic(false);
    }
  };

  const generateStock = async () => {
    if (!hasTopic) return;
    setSavingTopic(true);
    setErr("");
    try {
      await setWeeklyDigestTopic(topic);
      await load();
    } catch (e) {
      setErr(e instanceof Error ? e.message : "エラー");
    } finally {
      setSavingTopic(false);
    }
  };

  const markDone = async (id: string) => {
    setBusyDigestId(id);
    setErr("");
    try {
      await completeWeeklyDigest(id);
      setExpandedId("");
      await load();
    } catch (e) {
      setErr(e instanceof Error ? e.message : "エラー");
    } finally {
      setBusyDigestId("");
    }
  };

  const stockLabel = useMemo(() => L.digestStockCount(digests.length), [digests.length]);

  return (
    <section className="view">
      <div className="card">
        <h2 className="prints-subhead">
          <RubyHtml html={L.titleDigest} />
        </h2>
        <p className="muted">
          <RubyHtml html={L.digestLead} />
        </p>
        {err ? <p className="status">{err}</p> : null}

        {!hasTopic || editingTopic ? (
          <div className="digest-topic-editor">
            <label className="print-title-label" htmlFor="digest-topic-input">
              <RubyHtml html={L.digestTopicInputLabel} />
            </label>
            <input
              id="digest-topic-input"
              className="print-title-input"
              value={topicInput}
              onChange={(e) => setTopicInput(e.target.value)}
              placeholder={L.digestTopicPlaceholder}
            />
            <div className="prints-row-actions">
              <button type="button" className="btn btn-primary prints-inline-btn" disabled={!canSaveTopic || savingTopic} onClick={() => void saveTopic()}>
                <RubyHtml html={savingTopic ? L.newPrintSaving : L.digestSaveTopic} />
              </button>
              {hasTopic ? (
                <button
                  type="button"
                  className="btn btn-ghost prints-inline-btn"
                  disabled={savingTopic}
                  onClick={() => {
                    setEditingTopic(false);
                    setTopicInput(topic);
                  }}
                >
                  <RubyHtml html={L.digestCancelEdit} />
                </button>
              ) : null}
            </div>
          </div>
        ) : (
          <div className="digest-topic-current">
            <p>
              <strong>
                <RubyHtml html={L.digestTopicLabel} />
              </strong>
              : {topic}
            </p>
            <div className="prints-row-actions">
              <button type="button" className="btn btn-secondary prints-inline-btn" onClick={() => setEditingTopic(true)}>
                <RubyHtml html={L.digestChangeTopic} />
              </button>
            </div>
          </div>
        )}
        {autoGeneratedOnOpen ? (
          <p className="muted digest-auto-generated-note">
            <RubyHtml html={L.digestAutoGeneratedNotice} />
          </p>
        ) : null}
      </div>

      {hasTopic ? (
        <div className="card">
          <h3 className="prints-subhead">
            <RubyHtml html={stockLabel} />
          </h3>
          {loading ? <p className="muted">…</p> : null}
          {!loading && digests.length === 0 ? (
            <div>
              <p className="muted">
                <RubyHtml html={L.digestEmptyStock} />
              </p>
              <button type="button" className="btn btn-primary btn-lg" disabled={savingTopic} onClick={() => void generateStock()}>
                <RubyHtml html={savingTopic ? L.newPrintSaving : L.digestGenerateStock} />
              </button>
            </div>
          ) : null}
          <ul className="digest-list">
            {digests.map((d) => {
              const open = expandedId === d.id;
              return (
                <li key={d.id} className="digest-item">
                  <div className="digest-item-head">
                    <p className="digest-item-subtopic">
                      <strong>
                        <RubyHtml html={L.digestSubTopic} />
                      </strong>
                      : {d.subTopic}
                    </p>
                    <button
                      type="button"
                      className="btn btn-ghost prints-inline-btn"
                      onClick={() => setExpandedId(open ? "" : d.id)}
                    >
                      <RubyHtml html={open ? L.digestClose : L.digestOpen} />
                    </button>
                  </div>
                  <p className="muted">{open ? d.content : preview(d.content)}</p>
                  {open ? (
                    <button
                      type="button"
                      className="btn btn-primary btn-lg"
                      disabled={busyDigestId === d.id}
                      onClick={() => void markDone(d.id)}
                    >
                      <RubyHtml html={busyDigestId === d.id ? L.newPrintSaving : L.digestDoneRead} />
                    </button>
                  ) : null}
                </li>
              );
            })}
          </ul>
        </div>
      ) : null}
    </section>
  );
}
