package api

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"log"
	"net/http"
	"strings"

	"github.com/huydx/kokugo/internal/ai"
	"github.com/huydx/kokugo/internal/store"
)

const (
	digestStockMin = 1
	digestStockMax = 20
)

func (s *Server) GetWeeklyDigestTopic(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		s.err(w, http.StatusMethodNotAllowed, "GET のみ")
		return
	}
	dbs, err := s.Store.GetAppSettings(r.Context())
	if err != nil {
		s.err(w, http.StatusInternalServerError, err.Error())
		return
	}
	topic := strings.TrimSpace(dbs.DigestTopic)
	s.json(w, http.StatusOK, map[string]any{"topic": topic})
}

func (s *Server) PutWeeklyDigestTopic(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPut && r.Method != http.MethodPost {
		s.err(w, http.StatusMethodNotAllowed, "PUT または POST")
		return
	}
	var body struct {
		Topic string `json:"topic"`
	}
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		s.err(w, http.StatusBadRequest, "JSONが不正です")
		return
	}
	topic := strings.TrimSpace(body.Topic)
	if topic == "" {
		s.err(w, http.StatusBadRequest, "topic が必要です")
		return
	}
	patch := store.AppSettingsPatch{DigestTopic: &topic}
	if err := s.Store.PatchAppSettings(r.Context(), patch); err != nil {
		s.err(w, http.StatusInternalServerError, err.Error())
		return
	}
	if err := s.ensureWeeklyDigestStock(r.Context(), topic); err != nil {
		log.Printf("weekly_digest: ensure stock on topic update: %v", err)
	}
	s.json(w, http.StatusOK, map[string]any{"ok": true, "topic": topic})
}

func (s *Server) ListWeeklyDigests(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		s.err(w, http.StatusMethodNotAllowed, "GET のみ")
		return
	}
	dbs, err := s.Store.GetAppSettings(r.Context())
	if err != nil {
		s.err(w, http.StatusInternalServerError, err.Error())
		return
	}
	topic := strings.TrimSpace(dbs.DigestTopic)
	if topic == "" {
		s.json(w, http.StatusOK, map[string]any{
			"topic":   "",
			"digests": []store.WeeklyDigest{},
			"stock":   0,
		})
		return
	}
	list, err := s.Store.ListWeeklyDigestsByTopic(r.Context(), topic, store.WeeklyDigestStatusStocked, digestStockMax)
	if err != nil {
		s.err(w, http.StatusInternalServerError, err.Error())
		return
	}
	autoGeneratedOnOpen := false
	if len(list) < digestStockMin {
		if err := s.ensureWeeklyDigestStock(r.Context(), topic); err != nil {
			log.Printf("weekly_digest: ensure stock on list: %v", err)
		}
		list, _ = s.Store.ListWeeklyDigestsByTopic(r.Context(), topic, store.WeeklyDigestStatusStocked, digestStockMax)
		autoGeneratedOnOpen = len(list) > 0
	}
	s.json(w, http.StatusOK, map[string]any{
		"topic":               topic,
		"digests":             list,
		"stock":               len(list),
		"autoGeneratedOnOpen": autoGeneratedOnOpen,
	})
}

func (s *Server) CompleteWeeklyDigest(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		s.err(w, http.StatusMethodNotAllowed, "POST のみ")
		return
	}
	id := r.PathValue("id")
	if strings.TrimSpace(id) == "" {
		s.err(w, http.StatusBadRequest, "digest id が不正です")
		return
	}
	if err := s.Store.CompleteWeeklyDigest(r.Context(), id); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			s.err(w, http.StatusNotFound, "見つかりません")
			return
		}
		s.err(w, http.StatusInternalServerError, err.Error())
		return
	}
	dbs, err := s.Store.GetAppSettings(r.Context())
	if err == nil && strings.TrimSpace(dbs.DigestTopic) != "" {
		go func(topic string) {
			if err := s.ensureWeeklyDigestStock(context.Background(), topic); err != nil {
				log.Printf("weekly_digest: replenish after complete: %v", err)
			}
		}(strings.TrimSpace(dbs.DigestTopic))
	}
	s.json(w, http.StatusOK, map[string]any{"ok": true})
}

func (s *Server) ensureWeeklyDigestStock(ctx context.Context, topic string) error {
	topic = strings.TrimSpace(topic)
	if topic == "" {
		return nil
	}
	rt := s.lm()
	if rt.summaryChat == nil {
		return errors.New("digest generation requires summary chat backend")
	}
	current, err := s.Store.CountWeeklyDigestsByTopic(ctx, topic, store.WeeklyDigestStatusStocked)
	if err != nil {
		return err
	}
	if current >= digestStockMin {
		return nil
	}
	need := digestStockMin - current
	if need < 0 {
		need = 0
	}
	existing, err := s.Store.ListWeeklyDigestSubTopics(ctx, topic, 200)
	if err != nil {
		return err
	}
	for i := 0; i < need; i++ {
		gen, err := ai.GenerateWeeklyDigest(ctx, rt.summaryChat, rt.summaryModel, topic, existing)
		if err != nil {
			return err
		}
		row, err := s.Store.InsertWeeklyDigest(ctx, topic, gen.SubTopic, gen.Content)
		if err != nil {
			// Unique sub-topic conflicts are expected occasionally from model retries.
			continue
		}
		existing = append(existing, row.SubTopic)
	}
	return nil
}
